In [1]:
import pandas as pd
import fiona
import shapely 
from shapely.geometry import Point, shape
import glob
import numpy as np
from fiona import collection

In [2]:
CC3 = ['KWT', 'BHR', 'OMN', 'QAT', 'SAU', 'ARE', 'YEM', 'ISR', 'PSE', 'JOR', 'LBN', 'SYR',
       'EGY', 'IRN', 'TUR', 'IRQ']

path_to_shape = '/Users/sabine.a.joseph/Downloads/'
    
def filenames_per_country_list(country_code, path):
    folder_name = country_code + '_adm_shp/'
    return glob.glob(path_to_shape + folder_name + '/*.shp')

In [3]:
# load dataset
GDELT_snippet = '/Users/sabine.a.joseph/Documents/sabine.a.joseph/Documents/GDELT_Data/' + 'one_month_GDELT.csv'
df = pd.read_csv(GDELT_snippet, low_memory=False)
df = df[df['Actor1Code'].isin(CC3)]
df = df.reset_index()

# empty column for region
df['region']=np.nan

In [33]:
#for i in range(0, len(df.Actor1Code)):
for i in range(0, 100):
    filenames_per_country = filenames_per_country_list(df.Actor1Code[i], path_to_shape)
    
    # loop through all regions within country (dep. on N shapefiles for each region)
    for k in range(0, len(filenames_per_country)):
        
        with fiona.open(filenames_per_country[k], 'r') as fiona_collection:
            shapefile_record = next(iter(fiona_collection))
            shape = shapely.geometry.asShape(shapefile_record['geometry'])
            point = shapely.geometry.Point(float(df.Actor1Geo_Long[i]),
                                           float(df.Actor1Geo_Lat[i])) # longitude, latitude

        if shape.contains(point):
            df.loc[i, 'region'] = filenames_per_country[k][-12:-4]

        fiona_collection.close()

In [34]:
df[0:100]

,index,GLOBALEVENTID,SQLDATE,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL,region
0,66,636514780,20170314,201703,2017,2017.2027,ARE,DUBAI,ARE,NaN,...,4,"Mogadishu, Banaadir, Somalia",SO,SO02,2.06667,45.36670,-3227437,20170314,https://www.whaleoil.co.nz/2017/03/photo-of-th...,ARE_adm0
1,109,636515730,20170314,201703,2017,2017.2027,EGY,EGYPTIAN,EGY,NaN,...,4,"Moscow, Moskva, Russia",RS,RS48,55.75220,37.61560,-2960561,20170314,http://wsau.com/news/articles/2017/mar/13/excl...,EGY_adm0
2,110,636515733,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://wsau.com/news/articles/2017/mar/13/excl...,EGY_adm0
3,111,636515734,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Sidi Barrani, Matru?, Egypt",EG,EG22,31.61250,25.92550,-302847,20170314,http://www.dnaindia.com/world/report-exclusive...,EGY_adm0
4,112,636515735,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://wsau.com/news/articles/2017/mar/13/excl...,NaN
5,113,636515736,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Sidi Barrani, Matru?, Egypt",EG,EG22,31.61250,25.92550,-302847,20170314,http://www.dnaindia.com/world/report-exclusive...,NaN
6,114,636515737,20170314,201703,2017,2017.2027,EGY,ALEXANDRIA,EGY,NaN,...,4,"Alexandria, Al Iskandariyah, Egypt",EG,EG06,31.19810,29.91920,-290263,20170314,http://www.theadvocate.com/baton_rouge/news/co...,EGY_adm0
7,115,636515738,20170314,201703,2017,2017.2027,EGY,EGYPTIAN,EGY,NaN,...,4,"Moscow, Moskva, Russia",RS,RS48,55.75220,37.61560,-2960561,20170314,http://wsau.com/news/articles/2017/mar/13/excl...,EGY_adm0
8,116,636515741,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://wsau.com/news/articles/2017/mar/13/excl...,EGY_adm0
9,117,636515742,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Sidi Barrani, Matru?, Egypt",EG,EG22,31.61250,25.92550,-302847,20170314,http://www.dnaindia.com/world/report-exclusive...,EGY_adm0
10,118,636515743,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://wsau.com/news/articles/2017/mar/13/excl...,NaN
11,119,636515744,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Sidi Barrani, Matru?, Egypt",EG,EG22,31.61250,25.92550,-302847,20170314,http://www.dnaindia.com/world/report-exclusive...,NaN
12,120,636515745,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.wmcactionnews5.com/story/34737440/e...,EGY_adm0
13,121,636515746,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.mycentx.com/news/world-news/egypts-...,EGY_adm0
14,122,636515747,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.krdo.com/news/national-internationa...,EGY_adm0
15,123,636515748,20170314,201703,2017,2017.2027,EGY,ALEXANDRIA,EGY,NaN,...,4,"Alexandria, Al Iskandariyah, Egypt",EG,EG06,31.19810,29.91920,-290263,20170314,http://www.theadvocate.com/baton_rouge/news/co...,EGY_adm0
16,124,636515749,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.krdo.com/news/national-internationa...,EGY_adm0
17,125,636515750,20170314,201703,2017,2017.2027,EGY,ALEXANDRIA,EGY,NaN,...,4,"Alexandria, Al Iskandariyah, Egypt",EG,EG06,31.19810,29.91920,-290263,20170314,http://www.theadvocate.com/baton_rouge/news/co...,EGY_adm0
18,126,636515751,20170314,201703,2017,2017.2027,EGY,CAIRO,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.wmcactionnews5.com/story/34737440/e...,EGY_adm0
19,127,636515752,20170314,201703,2017,2017.2027,EGY,EGYPTIAN,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.dnaindia.com/world/report-egypt-s-f...,EGY_adm0
20,128,636515753,20170314,201703,2017,2017.2027,EGY,CAIRO,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.wmcactionnews5.com/story/34737440/e...,EGY_adm0
21,129,636515754,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.krdo.com/news/national-internationa...,EGY_adm0
22,130,636515755,20170314,201703,2017,2017.2027,EGY,CAIRO,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.krdo.com/news/national-internationa...,EGY_adm0
23,131,636515756,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.krdo.com/news/national-internationa...,EGY_adm0
24,132,636515757,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.dnaindia.com/world/report-egypt-s-f...,EGY_adm0
25,133,636515758,20170314,201703,2017,2017.2027,EGY,EGYPT,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,http://www.dnaindia.com/world/report-egypt-s-f...,EGY_adm0
26,134,636515759,20170314,201703,2017,2017.2027,EGY,EGYPTIAN,EGY,NaN,...,4,"Cairo, Al Qahirah, Egypt",EG,EG11,30.05000,31.25000,-290692,20170314,https://www.nytimes.com/reuters/2017/03/13/wor...,EGY_adm0
27,135,636515760,20170314,201703,2017,2017.2027,EGY,EGYPTIAN,EGY,NaN,...,4,"Moscow, Moskva, Russia",RS,RS48,55.75220,37.61560,-2960561,20170314,http://wsau.com/news/articles/2017/mar/13/excl...,EGY_adm0
28,136,636515761,20170314,201703,2017,2017.2027,EGY,EGYPTIAN,EGY,NaN,...,4,"Sidi Barrani, Matru?, Egypt",EG,EG22,31.61250,25.92550,-302847,20170314,http://wsau.com/news/articles/2017/mar/13/excl...,EGY_adm0
29,137,636515762,20170314,201703,2017,2017.2027,EGY,EGYPTIAN,EGY,NaN,...,4,"Sidi Barrani, Matru?, Egypt",EG,EG22,31.61250,25.92550,-302847,20170314,http://uk.reuters.com/article/uk-usa-russia-li...,EGY_adm0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,378,636517816,20170314,201703,2017,2017.2027,SAU,SAUDI ARABIAN,SAU,NaN,...,4,"Bali, Jawa Timur, Indonesia",ID,ID08,-7.10460,112.33700,10205777,20170314,http://www.canberratimes.com.au/comment/saudi-...,SAU_adm0
71,379,636517818,20170314,201703,2017,2017.2027,SAU,SAUDI,SAU,NaN,...,1,Saudi Arabia,SA,SA,25.00000,45.00000,SA,20170314,http://www.hellenicshippingnews.com/oil-bulls-...,SAU_adm0
72,380,636517819,20170314,201703,2017,2017.2027,SAU,SAUDI,SAU,NaN,...,1,Saudi Arabia,SA,SA,25.00000,45.00000,SA,20170314,http://www.hellenicshippingnews.com/oil-bulls-...,SAU_adm0
73,381,636517820,20170314,201703,2017,2017.2027,SAU,SAUDI,SAU,NaN,...,4,"Riyadh, Ar Riya?, Saudi Arabia",SA,SA10,24.64080,46.77280,-3093009,20170314,http://saudigazette.com.sa/saudi-arabia/muhamm...,SAU_adm0
74,382,636517821,20170314,201703,2017,2017.2027,SAU,SAUDI,SAU,NaN,...,3,"White House, District of Columbia, United States",US,USDC,38.89510,-77.03640,531871,20170314,http://saudigazette.com.sa/saudi-arabia/muhamm...,SAU_adm0
75,383,636517822,20170314,201703,2017,2017.2027,SAU,SAUDI ARABIA,SAU,NaN,...,3,"White House, District of Columbia, United States",US,USDC,38.89510,-77.03640,531871,20170314,http://saudigazette.com.sa/saudi-arabia/muhamm...,SAU_adm0
76,384,636517823,20170314,201703,2017,2017.2027,SAU,SAUDI ARABIA,SAU,NaN,...,3,"White House, District of Columbia, United States",US,USDC,38.89510,-77.03640,531871,20170314,http://saudigazette.com.sa/saudi-arabia/muhamm...,SAU_adm0
77,385,636517824,20170314,201703,2017,2017.2027,SAU,SAUDI,SAU,NaN,...,3,"Washington, District of Columbia, United States",US,USDC,38.89510,-77.03640,531871,20170314,http://saudigazette.com.sa/saudi-arabia/muhamm...,SAU_adm0
78,386,636517826,20170314,201703,2017,2017.2027,SAU,RIYADH,SAU,NaN,...,4,"Riyadh, Ar Riya?, Saudi Arabia",SA,SA10,24.64080,46.77280,-3093009,20170314,http://saudigazette.com.sa/saudi-arabia/muhamm...,SAU_adm0
79,387,636517827,20170314,201703,2017,2017.2027,SAU,SAUDI ARABIA,SAU,NaN,...,1,Saudi Arabia,SA,SA,25.00000,45.00000,SA,20170314,http://www.nasdaq.com/article/oil-settles-a-ta...,SAU_adm0
80,399,636517906,20170314,201703,2017,2017.2027,SYR,SYRIAN,SYR,NaN,...,2,"Hawaii, United States",US,USHI,21.10980,-157.53100,HI,20170314,http://www.kvoa.com/story/34753204/states-aimi...,SYR_adm0
81,400,636517907,20170314,201703,2017,2017.2027,SYR,SYRIAN,SYR,NaN,...,1,Syria,SY,SY,35.00000,38.00000,SY,20170314,http://thegardenisland.com/news/state-and-regi...,SYR_adm0
82,401,636517909,20170314,201703,2017,2017.2027,SYR,SYRIA,SYR,NaN,...,1,Syria,SY,SY,35.00000,38.00000,SY,20170314,http://reliefweb.int/report/burundi/human-righ...,SYR_adm0
83,402,636517911,20170314,201703,2017,2017.2027,SYR,SYRIAN,SYR,NaN,...,1,Syria,SY,SY,35.00000,38.00000,SY,20170314,http://thegardenisland.com/news/state-and-regi...,SYR_adm0
84,403,636517913,20170314,201703,2017,2017.2027,SYR,SYRIA,SYR,NaN,...,1,Sweden,SW,SW,62.00000,15.00000,SW,20170314,http://i1067.com/news/articles/2017/mar/13/pea...,SYR_adm0
85,404,636517917,20170314,201703,2017,2017.2027,SYR,SYRIA,SYR,NaN,...,4,"Damascus, Dimashq, Syria",SY,SY13,33.50000,36.30000,-2541260,20170314,http://www.irishsun.com/index.php/sid/252401494,SYR_adm0
86,405,636517918,20170314,201703,2017,2017.2027,SYR,SYRIA,SYR,NaN,...,4,"Raqqa, Ar Raqqah, Syria",SY,SY04,35.95000,39.01670,-2538949,20170314,https://www.defense.gov/News/Article/Article/1...,SYR_adm0
87,406,636517919,20170314,201703,2017,2017.2027,SYR,SYRIAN,SYR,NaN,...,4,"Raqqa, Ar Raqqah, Syria",SY,SY04,35.95000,39.01670,-2538949,20170314,https://www.defense.gov/News/Article/Article/1...,SYR_adm0
88,407,636517920,20170314,201703,2017,2017.2027,SYR,SYRIAN,SYR,NaN,...,4,"Raqqa, Ar Raqqah, Syria",SY,SY04,35.95000,39.01670,-2538949,20170314,https://www.defense.gov/News/Article/Article/1...,SYR_adm0
89,408,636517922,20170314,201703,2017,2017.2027,SYR,SYRIA,SYR,NaN,...,1,Iran,IR,IR,32.00000,53.00000,IR,20170314,http://news.trust.org/item/20170313203002-rltor/,NaN
90,409,636517923,20170314,201703,2017,2017.2027,SYR,SYRIA,SYR,NaN,...,1,Iran,IR,IR,32.00000,53.00000,IR,20170314,http://news.trust.org/item/20170313203002-rltor/,SYR_adm0
91,410,636517924,20170314,201703,2017,2017.2027,SYR,DAMASCUS,SYR,NaN,...,4,"Dublin, Dublin, Ireland",EI,EI07,53.33310,-6.24889,-1502554,20170314,http://www.irishsun.com/index.php/sid/252404207,NaN
92,411,636517925,20170314,201703,2017,2017.2027,SYR,DAMASCUS,SYR,NaN,...,4,"Clonakilty, Cork, Ireland",EI,EI04,51.62310,-8.87056,-1501724,20170314,http://www.irishsun.com/index.php/sid/252404211,SYR_adm0
93,412,636517926,20170314,201703,2017,2017.2027,SYR,DAMASCUS,SYR,NaN,...,4,"Dublin, Dublin, Ireland",EI,EI07,53.33310,-6.24889,-1502554,20170314,http://www.irishsun.com/index.php/sid/252404215,SYR_adm0
94,413,636517927,20170314,201703,2017,2017.2027,SYR,DAMASCUS,SYR,NaN,...,4,"Damascus, Dimashq, Syria",SY,SY13,33.50000,36.30000,-2541260,20170314,http://www.irishsun.com/index.php/sid/252404210,SYR_adm0
95,414,636517928,20170314,201703,2017,2017.2027,SYR,SYRIA,SYR,NaN,...,1,Ireland,EI,EI,53.00000,-8.00000,EI,20170314,http://www.irishsun.com/index.php/sid/252401494,SYR_adm0
96,415,636517929,20170314,201703,2017,2017.2027,SYR,DAMASCUS,SYR,NaN,...,1,Ireland,EI,EI,53.00000,-8.00000,EI,20170314,http://www.irishsun.com/index.php/sid/252404209,SYR_adm0
97,416,636517930,20170314,201703,2017,2017.2027,SYR,DAMASCUS,SYR,NaN,...,1,Ireland,EI,EI,53.00000,-8.00000,EI,20170314,http://www.irishsun.com/index.php/sid/252404213,NaN
98,417,636517936,20170314,201703,2017,2017.2027,SYR,SYRIA,SYR,NaN,...,1,Syria,SY,SY,35.00000,38.00000,SY,20170314,http://news.trust.org/item/20170313203002-rltor/,SYR_adm0
99,418,636517937,20170314,201703,2017,2017.2027,SYR,SYRIAN,SYR,NaN,...,1,Philippines,RP,RP,13.00000,122.00000,RP,20170314,http://i1067.com/news/articles/2017/mar/13/pea...,NaN

In [ ]:
##### test individual points
with fiona.open(filenames_per_country[1], 'r') as fiona_collection:
    shapefile_record = next(iter(fiona_collection))
    shape = shapely.geometry.asShape(shapefile_record['geometry'])
    point = shapely.geometry.Point(53.00000, 32.00000) # longitude, latitude

    if shape.contains(point):
        print "Found shape for point."

In [42]:
df.shape

(170878, 60)